### ISSUE TITLE
issue in chall 50

### ISSUE THREAD

**Issue by goonbamm** [arkilpatel/SVAMP#12]
Firstly, I appreciate your code and brilliant idea.

I found something strange in 'valid.json'.

    {
        "ID": "chal-50",
        "Body": "Nell collects cards. She had 309 baseball cards and 356 Ace cards. She gave some of her cards to Jeff and now has 415 baseball cards and Ace cards left.",
        "Question": "How many more baseball cards than Ace cards does Nell have?",
        "Equation": "( 415.0 - 149.0 )",
        "Answer": 266.0,
        "Type": "Subtraction"
    }

In Math Word Problem, costant is considered as the necessary quanty which does not appear in the problem like '149.0' in the example. But I have no idea how the constant '149.0' is calculated from the question. Please let me know if I misunderstood.

Thank you.

**Comment by arkilpatel** [comment]
Sorry, the chal-50 question appears to be invalid. Thanks for bringing it to my attention.

**Comment by goonbamm** [comment]
You are welcome. I hope you have nice day. Thank you.
